variables:
  DOCKER_REPOSITORY: registry.mender.io/northerntech/alvaldi-docs
  DOCKERFILE: Containerfile
  MULTIPLATFORM_BUILD: "true"
  MULTIPLATFORM_PLATFORMS: "linux/amd64,linux/arm64"
  GITHUB_STATUS_API_URL: "https://api.github.com/repos/NorthernTechHQ/$CI_PROJECT_NAME/statuses/$CI_COMMIT_SHA"
  DOCKER_HOST:
    value: 'tcp://docker:2376'
    description: "Required to run dind inside k8s runners with TLS"
  DOCKER_TLS_CERTDIR:
    value: '/certs'
    description: "The cert dir inside the gitlab runner. Don't change this."
  DOCKER_TLS_VERIFY:
    value: "1"
    description: "Enable TLS verification for docker in dind"
  DOCKER_CERT_PATH:
    value: "$DOCKER_TLS_CERTDIR/client"
    description: "Used for docker entrypoints. See https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4125"


include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-build.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-deploy.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'


stages:
  - build
  - publish
  - sync

# excludes non multiplatform build job
build:docker:
  rules:
    - when: never

# excludes non multiplatform build job
publish:image:
  rules:
    - when: never

publish:image-multiplatform:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(main|production)$/'

sync:image:
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
  variables:
    TARGET_MANIFEST_FILE: "kubernetes/alvaldi-docs/alvaldi-docs-deployment.yaml"
  dependencies:
    - publish:image-multiplatform

sync:image:staging:
  extends: sync:image
  dependencies:
    - publish:image-multiplatform
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  variables:
    TARGET_MANIFEST_FILE: "kubernetes/staging-alvaldi-docs/staging-alvaldi-docs-deployment.yaml"
