baseurl = "/"
languageCode = "en"
title = "Alvaldi Docs"
theme = "alvaldi"
copyright = "&copy; 2023 <a href=\"https://northern.tech\">Northern.tech</a> AS"
enableRobotsTXT = true

# Number of posts per page
[pagination]
pagerSize = 10

[taxonomies]
tag = "tags"

[markup]
[markup.highlight]
style = 'pygments'
codeFences = true
pygmentsCodeFences = true
